models/UnitKerja.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "unit_kerja".
 *
 * @property int $id
 * @property int|null $parent_id
 * @property int|null $jenjang_id
 * @property int|null $user_id
 * @property int|null $is_sent
 * @property string|null $jenis
 * @property string $nama
 * @property string|null $singkatan
 * @property string|null $surat
 * @property string|null $kode_prodi
 * @property string|null $email
 * @property string|null $penanggung_jawab
 *
 * @property User $user
 * @property User[] $users
 */
class UnitKerja extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'unit_kerja';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parent_id', 'jenjang_id', 'user_id', 'is_sent'], 'integer'],
            [['nama'], 'required'],
            [['jenis', 'nama'], 'string', 'max' => 100],
            [['singkatan'], 'string', 'max' => 20],
            [['surat'], 'string', 'max' => 5],
            [['kode_prodi'], 'string', 'max' => 10],
            [['email', 'penanggung_jawab'], 'string', 'max' => 150],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'parent_id' => Yii::t('app', 'Parent ID'),
            'jenjang_id' => Yii::t('app', 'Jenjang ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'is_sent' => Yii::t('app', 'Is Sent'),
            'jenis' => Yii::t('app', 'Type'),
            'nama' => Yii::t('app', 'Name'),
            'singkatan' => Yii::t('app', 'Abbreviation'),
            'surat' => Yii::t('app', 'Letter'),
            'kode_prodi' => Yii::t('app', 'Prodi Code'),
            'email' => Yii::t('app', 'Email'),
            'penanggung_jawab' => Yii::t('app', 'Person Responsible'),
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    /**
     * Gets query for [[Users]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::class, ['unit_kerja_id' => 'id']);
    }
}

controllers/UnitKerjaController.php
<?php

namespace app\controllers;

use app\helpers\MyHelper;
use Yii;
use app\models\UnitKerja;
use app\models\UnitKerjaSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\httpclient\Client;
use yii\web\Response;

/**
 * UnitKerjaController implements the CRUD actions for UnitKerja model.
 */
class UnitKerjaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    throw new \yii\web\ForbiddenHttpException('You are not allowed to access this page');
                },
                'only' => ['create', 'update', 'delete', 'index', 'ajax-import', 'ajax-import-simuda', 'ajax-send'],
                'rules' => [
                    [
                        'actions' => [
                            'create', 'update', 'delete', 'index', 'ajax-import', 'ajax-import-simuda', 'ajax-send'
                        ],
                        'allow' => true,
                        'roles' => ['theCreator', 'admin'],
                    ],

                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all UnitKerja models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UnitKerjaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UnitKerja model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UnitKerja model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UnitKerja();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Data tersimpan");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionAjaxImport()
    {
        $results = [];
        $api_baseurl = Yii::$app->params['api_baseurl'];
        $client = new Client(['baseUrl' => $api_baseurl]);
        $client_token = Yii::$app->params['client_token'];
        $headers = ['x-access-token' => $client_token];

        $response = $client->get('/simpeg/list/unitkerja', [], $headers)->send();
        $list_dosen = [];
        $list_target_rasio = [];
        $list_jenjang = MyHelper::listJenjangStudi();
        if ($response->isOk) {
            $counter = 0;
            $list_unit = $response->data['values'];
            foreach ($list_unit as $unit) {
                // echo '<pre>';print_r($list_unit);die;

                $u = UnitKerja::findOne($unit['id']);
                if (empty($u)) {
                    $u = new UnitKerja;
                    $u->id = $unit['id'];
                }

                $u->nama = $unit['nama'];
                if ($u->save()) {
                    $counter++;
                } else {
                    $err = MyHelper::logError($u);
                    print_r($err);
                    exit;
                }
            }

            $results = [
                'code' => 200,
                'message' => $counter . ' data successfully imported'
            ];
        }

        echo \yii\helpers\Json::encode($results);
        exit;
    }

    public function actionAjaxImportSimuda()
    {
        $results = [];
        $api_baseurl = Yii::$app->params['api_simudaurl'];
        $client = new Client(['baseUrl' => $api_baseurl]);
        $client_token = Yii::$app->params['client_token'];
        $headers = ['x-access-token' => $client_token];

        $response = $client->get('/api/get-unit-kerja', [], $headers)->send();
        $list_dosen = [];
        $list_target_rasio = [];
        $list_jenjang = MyHelper::listJenjangStudi();
        if ($response->isOk) {
            $counter = 0;
            $list_unit = $response->data;
            foreach ($list_unit as $unit) {

                $u = UnitKerja::findOne($unit['id']);
                if (empty($u)) {
                    $u = new UnitKerja;
                    $u->id = $unit['id'];
                }

                $u->nama = $unit['nama'];
                $u->jenis = $unit['jenis'];
                $u->singkatan = $unit['singkatan'];
                $u->email = $unit['email'];
                $u->penanggung_jawab = $unit['penanggung_jawab'];
                
                if ($u->save()) {
                    $counter++;
                } else {
                    $err = MyHelper::logError($u);
                    print_r($err);
                    exit;
                }
            }

            $results = [
                'code' => 200,
                'message' => $counter . ' data successfully imported'
            ];
        }

        echo json_encode($results);
        exit;
    }

    public function actionAjaxSend()
    {
        $results = [];

        $errors = '';
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        $dataPost = $_POST;

        $model = $this->findModel($dataPost['id']);


        try {
            if (!empty($dataPost)) {


                $model->is_sent = 1;
                $model->save();

                // Add User Auditee...

                $user = User::findOne([
                    'unit_kerja_id' => $model->id,
                ]);

                // echo '<pre>';print_r($user);die;
                $is_user = false;
                if (empty($user)) {
                    $user = new User;
                    $is_user = true;
                }

                $password = MyHelper::getRandomString(8, 8, true, false, false);

                $user->username = $model->email;
                $user->email = $model->email;
                $user->nama = $model->nama;
                $user->unit_kerja_id = $model->id;

                $user->setPassword($password);
                $user->status = User::STATUS_ACTIVE;
                $user->access_role = 'unitKerja';
                $user->created_at = date('Y-m-d');
                $user->updated_at = date('Y-m-d');

                $auth = Yii::$app->authManager;
                $oldRole = $auth->getRole('unitKerja');
                
                $user->access_role = $oldRole->name;

                // echo '<pre>';print_r($user);die;
                if ($user->save()) {

                    if ($is_user == true)
                        $auth->assign($oldRole, $user->id);

                    $to = MyHelper::sendEmail($user->email);

                    $emailTemplate = $this->renderPartial('email', [
                        'user' => $user,
                        'password' => $password
                    ]);

                    Yii::$app->mailer->compose()
                        ->setTo($to)
                        ->setFrom([Yii::$app->params['supportEmail'] => 'SARPRAS UNIDA Gontor'])
                        ->setSubject('[SARPRAS] Account Information')
                        ->setHtmlBody($emailTemplate)
                        ->send();


                    // $toBpm = MyHelper::emailBpm();
                    // Yii::$app->mailer->compose()
                    //     ->setTo($toBpm)
                    //     ->setFrom([Yii::$app->params['supportEmail'] => 'SIMUDA UNIDA Gontor'])
                    //     ->setSubject('[SIMUDA] Account Information')
                    //     ->setHtmlBody($emailTemplate)
                    //     ->send();
                        
                } else {
                    $errors .= MyHelper::logError($model);
                    throw new \Exception;
                }

                $transaction->commit();
                $results = [
                    'code' => 200,
                    'message' => 'Data successfully updated'
                ];
            } else {
                $errors .= 'Oops, you cannot POST empty data';
                throw new \Exception;
            }
        } catch (\Exception $e) {
            $transaction->rollBack();
            $errors .= $e->getMessage();
            // $errors .= 'Oops, your data is incomplete, please complete the data';

            $results = [
                'code' => 500,
                'message' => $errors
            ];
        } catch (\Throwable $e) {
            $transaction->rollBack();
            $errors .= $e->getMessage();
            $results = [
                'code' => 500,
                'message' => $errors
            ];
        }
        echo json_encode($results);
        exit;
    }

    /**
     * Updates an existing UnitKerja model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', "Data tersimpan");
            return $this->redirect(['view', 'id' => $model->id]);

views/unit-kerja/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerja */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="unit-kerja-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'parent_id',['options' => ['tag' => false]])->textInput() ?>

    <?= $form->field($model, 'jenjang_id',['options' => ['tag' => false]])->textInput() ?>

    <?= $form->field($model, 'is_sent',['options' => ['tag' => false]])->textInput() ?>

    <?= $form->field($model, 'jenis',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true]) ?>

    <?= $form->field($model, 'nama',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true]) ?>

    <?= $form->field($model, 'singkatan',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true]) ?>

    <?= $form->field($model, 'surat',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true]) ?>

    <?= $form->field($model, 'kode_prodi',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true]) ?>

    <?= $form->field($model, 'email',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true]) ?>

    <?= $form->field($model, 'penanggung_jawab',['options' => ['tag' => false]])->textInput(['class'=>'form-control','maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/unit-kerja/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerjaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="unit-kerja-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'parent_id') ?>

    <?= $form->field($model, 'jenjang_id') ?>

    <?= $form->field($model, 'is_sent') ?>

    <?php // echo $form->field($model, 'jenis') ?>

    <?php // echo $form->field($model, 'nama') ?>

    <?php // echo $form->field($model, 'singkatan') ?>

    <?php // echo $form->field($model, 'surat') ?>

    <?php // echo $form->field($model, 'kode_prodi') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'penanggung_jawab') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/unit-kerja/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\UnitKerja */

$this->title = Yii::t('app', 'Create Divission');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Divission'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<h3><?= Html::encode($this->title) ?></h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body ">



    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    	   </div>
        </div>
    </div>
</div>

views/unit-kerja/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use richardfan\widget\JSRegister;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UnitKerjaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Divissions');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body ">

                <p>
                    <?= Html::a('<i class="fa fa-plus"></i> Add Divission', ['create'], ['class' => 'btn btn-success']); ?>
                    <?= Html::a('<i class="fa fa-download"></i> Import Data From API', 'javascript:void(0)', ['class' => 'btn btn-primary btn-import']); ?>
                    <?= Html::a('<i class="fa fa-book"></i> Import Data From SIMUDA', 'javascript:void(0)', ['class' => 'btn btn-primary btn-import-simuda']); ?>
                </p>
                <?php
                $gridColumns = [
                    [
                        'class' => 'kartik\grid\SerialColumn',
                        'contentOptions' => ['class' => 'kartik-sheet-style'],
                        'width' => '36px',
                        'pageSummary' => 'Total',
                        'pageSummaryOptions' => ['colspan' => 6],
                        'header' => '',
                        'headerOptions' => ['class' => 'kartik-sheet-style']
                    ],
                    // 'id',
                    // 'parent_id',
                    // 'jenjang_id',
                    // 'is_sent',
                    'nama',
                    'jenis',
                    'singkatan',
                    // 'surat',
                    // 'kode_prodi',
                    'email:email',
                    // 'penanggung_jawab',
                    'penanggung_jawab',
                    ['class' => 'yii\grid\ActionColumn']
                ]; ?>
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'columns' => $gridColumns,
                    'containerOptions' => ['style' => 'overflow: auto'],
                    'headerRowOptions' => ['class' => 'kartik-sheet-style'],
                    'filterRowOptions' => ['class' => 'kartik-sheet-style'],
                    'containerOptions' => ['style' => 'overflow: auto'],
                    'beforeHeader' => [
                        [
                            'columns' => [
                                ['content' => $this->title, 'options' => ['colspan' => 14, 'class' => 'text-center warning']], //cuma satu 
                            ],
                            'options' => ['class' => 'skip-export']
                        ]
                    ],
                    'exportConfig' => [
                        GridView::PDF => ['label' => 'Save as PDF'],
                        GridView::EXCEL => ['label' => 'Save as EXCEL'], //untuk menghidupkan button export ke Excell
                        GridView::HTML => ['label' => 'Save as HTML'], //untuk menghidupkan button export ke HTML
                        GridView::CSV => ['label' => 'Save as CSV'], //untuk menghidupkan button export ke CVS
                    ],

                    'toolbar' =>  [
                        '{export}',

                        '{toggleData}' //uncoment untuk menghidupkan button menampilkan semua data..
                    ],
                    'toggleDataContainer' => ['class' => 'btn-group mr-2'],
                    // set export properties
                    'export' => [
                        'fontAwesome' => true
                    ],
                    'pjax' => true,
                    'bordered' => true,
                    'striped' => true,
                    // 'condensed' => false,
                    // 'responsive' => false,
                    'hover' => true,
                    // 'floatHeader' => true,
                    // 'showPageSummary' => true, //true untuk menjumlahkan nilai di suatu kolom, kebetulan pada contoh tidak ada angka.
                    'panel' => [
                        'type' => GridView::TYPE_PRIMARY
                    ],
                ]); ?>

            </div>
        </div>
    </div>

</div>

<?php JSRegister::begin() ?>
<script>
    $(document).on("click", ".btn-import", function(e) {
        e.preventDefault();

        $.ajax({
            url: "/unit-kerja/ajax-import",
            type: "POST",
            async: true,
            error: function(e) {
                console.log(e.responseText)
            },
            beforeSend: function() {
                Swal.showLoading()
            },
            success: function(data) {
                Swal.close()
                var hasil = $.parseJSON(data)
                if (hasil.code == 200) {
                    Swal.fire({
                        title: 'Yeay!',
                        icon: 'success',
                        text: hasil.message
                    }).then((hasil) => {
                        if (hasil) {
                            location.reload();
                        }
                    });
                } else {
                    Swal.fire({
                        title: 'Oops!',
                        icon: 'error',
                        text: hasil.message
                    })
                }
            }
        })
    });

    
    $(document).on("click", ".btn-import-simuda", function(e) {
        e.preventDefault();

        $.ajax({
            url: "/unit-kerja/ajax-import-simuda",
            type: "POST",
            async: true,
            error: function(e) {
                console.log(e.responseText)
            },
            beforeSend: function() {
                Swal.showLoading()
            },
            success: function(data) {
                Swal.close()
                var hasil = $.parseJSON(data)
                if (hasil.code == 200) {
                    Swal.fire({
                        title: 'Yeay!',
                        icon: 'success',
                        text: hasil.message
                    }).then((hasil) => {
                        if (hasil) {
                            location.reload();
                        }
                    });
                } else {
                    Swal.fire({
                        title: 'Oops!',
                        icon: 'error',
                        text: hasil.message
                    })
                }
            }
        })
    });
</script>
<?php JSRegister::end() ?>

views/unit-kerja/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerja */

$this->title = Yii::t('app', 'Update Divission: ' . $model->id);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Divissions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<h3><?= Html::encode($this->title) ?></h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body ">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
           </div>
        </div>
    </div>
</div>

views/unit-kerja/view.php
<?php

use richardfan\widget\JSRegister;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UnitKerja */

$this->title = $model->nama;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Divissions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="block-header">
    <h2><?= Html::encode($this->title) ?></h2>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
                <?= Html::a('<i class="fa fa-send"></i> Create & Send Account', 'javascript:void(0)', ['class' => 'btn btn-primary', 'id' => 'btn-send', 'data-unit' => $model->id]) ?>

                <form action="" id="form-unit">
                    <?= Html::hiddenInput('id', $model->id, ['id' => 'id_unit']) ?>
                </form>
                
            </div>

            <div class="panel-body ">

                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        // 'id',
                        // 'parent_id',
                        // 'jenjang_id',
                        // 'is_sent',
                        'jenis',
                        'nama',
                        'singkatan',
                        // 'surat',
                        // 'kode_prodi',
                        'email:email',
                        'penanggung_jawab',
                    ],
                ]) ?>

            </div>
        </div>

    </div>
</div>

<?php JSRegister::begin() ?>
<script>
    $(document).on("click", "#btn-send", function(e) {
        e.preventDefault();

        var obj = $("#form-unit").serialize()

        $.ajax({
            url: "/unit-kerja/ajax-send",
            type: "POST",
            async: true,
            data: obj,
            error: function(e) {
                console.log(e.responseText)
            },
            beforeSend: function() {
                Swal.fire({
                    title: "Please wait",
                    html: "Sending Email..",

                    allowOutsideClick: false,
                    onBeforeOpen: () => {
                        Swal.showLoading()
                    },

                })
            },
            success: function(data) {
                Swal.close()
                var hasil = $.parseJSON(data)
                if (hasil.code == 200) {
                    Swal.fire({
                        title: 'Yeay!',
                        icon: 'success',
                        text: hasil.message
                    }).then(res => {
                        window.location.reload()
                    });

                    $.pjax.reload({
                        container: "#pjax-container"
                    });
                } else {
                    Swal.fire({
                        title: 'Oops!',
                        icon: 'error',
                        text: hasil.message
                    })
                }
            }
        })
    });
</script>
<?php JSRegister::end() ?>