controllers/UserController.php
<?php

namespace app\controllers;

use app\helpers\MyHelper;
use Yii;
use app\models\AuthAssignment;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\ServerErrorHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    throw new \yii\web\ForbiddenHttpException('You are not allowed to access this page');
                },
                'only' => ['create', 'update', 'delete', 'index'],
                'rules' => [
                    [
                        'actions' => [
                            'create', 'update', 'delete', 'index'
                        ],
                        'allow' => true,
                        'roles' => ['theCreator'],
                    ],

                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionAjaxAddRole()
    {
        $dataPost = $_POST['dataPost'];
        $results = [];
        $user = $this->findModel($dataPost['user_id']);

        $auth = Yii::$app->authManager;
        if (!empty($user)) {
            $auth = Yii::$app->authManager;

            $newRole = $auth->getRole($dataPost['item_name']);

            $userId = $user->getId();
            $info = $auth->assign($newRole, $userId);

            $errors = '';


            if (!$info) {
                $errors .= 'There was some error while saving user role.';
                throw new \Exception;
            }


            $results = [
                'code' => 200,
                'message' => 'Data added'
            ];
        } else {
            $results = [
                'code' => 500,
                'message' => 'User not found'
            ];
        }

        echo json_encode($results);
        exit;
    }

    public function actionAjaxDeleteRole()
    {
        $dataPost = $_POST['dataPost'];
        $results = [];
        $user = $this->findModel($dataPost['user_id']);


        if (!empty($user)) {
            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            $errors = '';
            try {
                $items = AuthAssignment::find()->where([
                    'user_id' => $user->id
                ])->all();

                if (count($items) > 0) {


                    if ($user->access_role != $dataPost['item_name']) {
                        $auth = Yii::$app->authManager;
                        if ($roles = $auth->getRolesByUser($user->id)) {
                            // it's enough for us the get first assigned role name
                            $role = '';
                            foreach ($roles as $r) {

                                if ($r->name == $dataPost['item_name']) {
                                    $role = $r->name;
                                    break;
                                }
                            }
                        }

                        // print_r($roles);exit;

                        // remove role if user had it
                        if (isset($role)) {

                            $info = $auth->revoke($auth->getRole($role), $user->id);
                        }

                        if (!$info) {
                            $errors .= 'Something wrong when deleting role';
                            throw new \Exception;
                        }

                        $transaction->commit();
                        $results = [
                            'code' => 200,
                            'message' => 'Role deleted'
                        ];
                    } else {
                        $errors .= 'Cannot delete assigned role';
                        throw new \Exception;
                    }
                } else {
                    $errors .= 'Cannot delete the last role';
                    throw new \Exception;
                }
            } catch (\Exception $e) {
                $errors .= $e->getMessage();
                $transaction->rollBack();

                $results = [
                    'code' => 500,
                    'message' => $errors
                ];
            } catch (\Throwable $e) {
                $errors .= $e->getMessage();
                $transaction->rollBack();
                $results = [
                    'code' => 500,
                    'message' => $errors
                ];
            }
        } else {
            $results = [
                'code' => 500,
                'message' => 'User not found'
            ];
        }

        echo json_encode($results);
        exit;
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (Yii::$app->request->post('hasEditable')) {

            // instantiate your book model for saving
            $id = Yii::$app->request->post('editableKey');
            $model = User::findOne($id);

            // store a default json response as desired by editable
            $out = json_encode(['output' => '', 'message' => '']);


            $posted = current($_POST['User']);
            $post = ['User' => $posted];
            if ($model->load($post)) {
                if ($model->save()) {
                    $out = json_encode(['output' => '', 'message' => '']);
                } else {
                    $errors = \app\helpers\MyHelper::logError($model);
                    $out = json_encode(['output' => '', 'message' => $errors]);
                }
            }

            echo $out;

            return;
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionCreate()
    {

        $user = new User(['scenario' => 'create']);

        if (!$user->load(Yii::$app->request->post())) {
            return $this->render('create', ['user' => $user]);
        }

        $pwd = $user->password;
        $user->setPassword($pwd);
        $user->generateAuthKey();
        $user->status = '10';
        $user->access_role = $user->access_role;

        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();

        if ($user->validate()) {
            try {

                $user->created_at = strtotime(date('YmdHis'));
                $user->updated_at = strtotime(date('YmdHis'));

                if ($user->save()) {
                    $auth = Yii::$app->authManager;
                    $role = $auth->getRole($user->access_role);
                    $info = $auth->assign($role, $user->getId());

                    if (!$info)
                        throw new \Exception('There was some error while saving user role.');

                    $transaction->commit();

                    Yii::$app->session->setFlash('success', Yii::t('app', 'You have successfuly add a user'));
                } else {
                    $errors = MyHelper::logError($user);
                    Yii::$app->session->setFlash('error', Yii::t('app', $errors));
                }
            } catch (\Exception $e) {
                $transaction->rollBack();
                $errors = $e->getMessage();

                Yii::$app->session->setFlash('error', Yii::t('app', $errors));
            }
        } else
            return $this->redirect('index');
        // return $this->render('login');
        // } else {
        //     return $this->goBack();
        // }

        return $this->redirect('index');
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $user = $this->findModel($id);

        $auth = Yii::$app->authManager;

        $authItems = \app\models\AuthItem::find()->select(['name'])->all();

        // get user role if he has one  
        $roles = $auth->getRolesByUser($id);
        $role = $user->access_role;

        // if user has role, set oldRole to that role name, else offer 'member' as sensitive default
        $oldRole = (isset($role)) ? $auth->getRole($role) : $auth->getRole('member');

        // set property item_name of User object to this role name, so we can use it in our form
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        $counter = 0;
        $errors = '';
        try {
            if (!$user->load(Yii::$app->request->post())) {
                return $this->render('update', [
                    'user' => $user,
                    'role' => $user->access_role,
                    'authItems' => $authItems
                ]);
            }

views/user/_form.php
<?php
use app\rbac\models\AuthItem;
use kartik\password\PasswordInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use kartik\depdrop\DepDrop;
use kartik\select2\Select2;
use yii\jui\AutoComplete;
use yii\web\JsExpression;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $user app\models\User */
/* @var $form yii\widgets\ActiveForm */

$list_roles = ArrayHelper::map(AuthItem::getRoles(),'name','name');

?>
<?php foreach (AuthItem::getRoles() as $item_name): ?>
            <?php $roles[$item_name->name] = $item_name->name ?>
        <?php endforeach ?>
<style>
.modal-dialog{
    top: 50%;
    margin-top: -250px; 
}

</style>
<div class="panel">
  <div class="panel-heading">
    <h3 class="panel-title"><?=$this->title;?></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">

      <?php $form = ActiveForm::begin(['id' => 'form-user']); ?>
          <?= $form->errorSummary($user,['header'=>'<div class="alert alert-danger">','footer'=>'</div>']);?>
          <?= $form->field($user, 'username')->textInput(
                  ['placeholder' => Yii::t('app', 'Create username'), 'autofocus' => true]) ?>

          <?= $form->field($user, 'uuid')->textInput(
                  ['placeholder' => Yii::t('app', 'UUID')]) ?>
          
          <?= $form->field($user, 'email')->input('email', ['placeholder' => Yii::t('app', 'Enter e-mail')]) ?>

          <?php if ($user->scenario === 'create'): ?>

              <?= $form->field($user, 'password')->widget(PasswordInput::classname(), 
                  ['options' => ['placeholder' => Yii::t('app', 'Create password')]]) ?>

          <?php else: ?>

              <?= $form->field($user, 'password')->widget(PasswordInput::classname(),
                       ['options' => ['placeholder' => Yii::t('app', 'Change password ( if you want )')]]) ?> 

          <?php endif ?>

      
        
          
          <?= $form->field($user, 'access_role')->widget(Select2::classname(), [
              'data' => $roles,

              'options'=>['placeholder'=>Yii::t('app','- Pilih Role -')],
              'pluginOptions' => [
                  'allowClear' => true,
              ],
          ])?>
            
      
            <?= $form->field($user, 'status')->dropDownList($user->statusList) ?>

          
            <div class="form-group">
              <label>NIM (*<small>Isikan NIM jika Mahasiswa</small>)</label>
          <?= $form->field($user, 'nim',['options' => ['tag' => false]])->input('nim', ['placeholder' => Yii::t('app', 'Enter ID'),'id'=>'nim'])->label(false) ?>
                  
              </div>
        

      <div class="form-group">     
          <?= Html::submitButton($user->isNewRecord ? Yii::t('app', 'Create') 
              : Yii::t('app', 'Update'), ['class' => $user->isNewRecord 
              ? 'btn btn-success' : 'btn btn-primary']) ?>

          <?= Html::a(Yii::t('app', 'Cancel'), ['user/index'], ['class' => 'btn btn-default']) ?>
      </div>

      <?php ActiveForm::end(); ?>
    </div>


    <?php 
    if(Yii::$app->user->can('theCreator'))
    {


    ?>
     <div class="col-md-6">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Role</th>
            <th>Option</th>
          </tr>
        </thead>
        <tbody>
          <?php 
          foreach($user->authAssignments as $role)
          {
          ?>
          <tr>
            <td><?=$role->item_name;?></td>
            <td><?=Html::a('<i class="fa fa-trash"></i> Remove','javascript:void(0)',['class'=>'btn btn-danger btn-remove-role','data-item'=>$role->item_name,'data-user'=>$user->id]);?></td>
          </tr>
          <?php 
          }
          ?>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2">
              <?=Html::a('<i class="fa fa-plus"></i> Add a Role','javascript:void(0)',['class'=>'btn btn-success','id'=>'btn-add-role']);?>
            </td>
          </tr>
        </tfoot>
      </table>
     
     </div>
     <?php 
    }
     ?>
  </div>

  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Data Role</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <input type="hidden" id="user_id" value="<?=$user->id;?>">
        <?=Html::dropDownList('item_name','',$list_roles,['id'=>'item_name','class'=>'form-control']);?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="btn-save">Add this role</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
<?php 

$script = ' 
$(document).on("click","#btn-add-role",function(e){
  e.preventDefault()

  $("#exampleModal").modal("show");

  

})

$(document).on(\'change\',\'#dosen\',function(e){
    e.preventDefault();
    $("#nim").val($(this).val());
    
});

$(document).on("click","#btn-save",function(e){
  e.preventDefault()

  var obj = new Object;
  obj.user_id = $("#user_id").val();
  obj.item_name = $("#item_name").val();
  
  $.ajax({
      type: \'POST\',
      url: "'.Url::to(['user/ajax-add-role']).'",
      data: {
          dataPost : obj
      },
      async: true,
      error : function(e){
        Swal.hideLoading();
        

      },
      beforeSend: function(){
        Swal.showLoading();
      },
      success: function (data) {
        var hasil = $.parseJSON(data)
        if(hasil.code == 200){
      
          Swal.fire({
            title: \'Yeay!\',
            icon: \'success\',
            text: hasil.message
          }).then((result) => {
            if (result.value) {
              location.reload(); 
            }
          });
        }

        else{
          Swal.fire({
            title: \'Oops!\',
            icon: \'error\',
            text: hasil.message
          }).then((result) => {
            if (result.value) {
              location.reload(); 
            }
          });
        }
      }
  })
})


$(document).on("click",".btn-remove-role",function(e){
  e.preventDefault()



  var obj = new Object;
  obj.user_id = $(this).data("user");
  obj.item_name = $(this).data("item");
  
  $.ajax({
      type: \'POST\',
      url: "'.Url::to(['user/ajax-delete-role']).'",
      data: {
          dataPost : obj
      },
      async: true,
      error : function(e){
        Swal.hideLoading();
        

      },
      beforeSend: function(){
        Swal.showLoading();
      },
      success: function (data) {
        var hasil = $.parseJSON(data)
        if(hasil.code == 200){
      
          Swal.fire({
            title: \'Yeay!\',
            icon: \'success\',
            text: hasil.message
          }).then((result) => {
            if (result.value) {
              location.reload(); 
            }
          });
        }

        else{
          Swal.fire({
            title: \'Oops!\',
            icon: \'error\',
            text: hasil.message
          }).then((result) => {
            if (result.value) {
              location.reload(); 
            }
          });
        }
      }
  })
})

';
if(Yii::$app->user->can('Mahasiswa'))
{
$script .= '
  setTimeout(function(){ 
    $("#nim").val("'.$user->nim.'");
  }, 500);
  
';
}
$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'uuid') ?>

    <?php // echo $form->field($model, 'access_role') ?>

    <?php // echo $form->field($model, 'nim') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body ">



    <?= $this->render('_form', [
        'user' => $user,
    ]) ?>
    	   </div>
        </div>
    </div>
</div>

views/user/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;

$list_status = ['10' => 'Aktif', '2' => 'Non-Aktif'];
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body ">

                <p>
                    <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
                </p>
                <?php
                $gridColumns = [
                    [
                        'class' => 'kartik\grid\SerialColumn',
                        'contentOptions' => ['class' => 'kartik-sheet-style'],
                        'width' => '36px',
                        'pageSummary' => 'Total',
                        'pageSummaryOptions' => ['colspan' => 6],
                        'header' => '',
                        'headerOptions' => ['class' => 'kartik-sheet-style']
                    ],

                    'username',
                    // 'auth_key',
                    // 'password_hash',
                    // 'password_reset_token',
                    'email:email',
                    [
                        'class' => 'kartik\grid\EditableColumn',
                        'attribute' => 'status',
                        'filter' => $list_status,
                        'readonly' => !Yii::$app->user->can('theCreator'),
                        'value' => function ($data) use ($list_status) {
                            return $list_status[$data->status];
                        },
                        'editableOptions' => [
                            'data' => $list_status,
                            'inputType' => \kartik\editable\Editable::INPUT_DROPDOWN_LIST,
                        ],
                    ],
                    [
                        'class' => 'kartik\grid\EditableColumn',
                        'attribute' => 'uuid',
                        'readonly' => !Yii::$app->user->can('theCreator'),
                        'editableOptions' => [
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                        ],
                    ],
                    'access_role',
                    [
                        'class' => 'kartik\grid\EditableColumn',
                        'attribute' => 'nim',
                        'readonly' => !Yii::$app->user->can('theCreator'),
                        'editableOptions' => [
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                        ],
                    ],
                    //'created_at',
                    //'updated_at',
                    ['class' => 'yii\grid\ActionColumn']
                ]; ?>
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'columns' => $gridColumns,
                    'containerOptions' => ['style' => 'overflow: auto'],
                    'headerRowOptions' => ['class' => 'kartik-sheet-style'],
                    'filterRowOptions' => ['class' => 'kartik-sheet-style'],
                    'containerOptions' => ['style' => 'overflow: auto'],
                    'beforeHeader' => [
                        [
                            'columns' => [
                                ['content' => $this->title, 'options' => ['colspan' => 14, 'class' => 'text-center warning']], //cuma satu 
                            ],
                            'options' => ['class' => 'skip-export']
                        ]
                    ],
                    'exportConfig' => [
                        GridView::PDF => ['label' => 'Save as PDF'],
                        GridView::EXCEL => ['label' => 'Save as EXCEL'], //untuk menghidupkan button export ke Excell
                        GridView::HTML => ['label' => 'Save as HTML'], //untuk menghidupkan button export ke HTML
                        GridView::CSV => ['label' => 'Save as CSV'], //untuk menghidupkan button export ke CVS
                    ],

                    'toolbar' =>  [
                        '{export}',

                        '{toggleData}' //uncoment untuk menghidupkan button menampilkan semua data..
                    ],
                    'toggleDataContainer' => ['class' => 'btn-group mr-2'],
                    // set export properties
                    'export' => [
                        'fontAwesome' => true
                    ],
                    'pjax' => true,
                    'bordered' => true,
                    'striped' => true,
                    // 'condensed' => false,
                    // 'responsive' => false,
                    'hover' => true,
                    // 'floatHeader' => true,
                    // 'showPageSummary' => true, //true untuk menjumlahkan nilai di suatu kolom, kebetulan pada contoh tidak ada angka.
                    'panel' => [
                        'type' => GridView::TYPE_PRIMARY
                    ],
                ]); ?>

            </div>
        </div>
    </div>

</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Update User: ' . $user->id);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $user->id, 'url' => ['view', 'id' => $user->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body ">
    <?= $this->render('_form', [
        'user' => $user,
    ]) ?>
           </div>
        </div>
    </div>
</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="block-header">
    <h2><?= Html::encode($this->title) ?></h2>
</div>
<div class="row">
   <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>

            <div class="panel-body ">
        
<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email:email',
            'status',
            'uuid',
            'access_role',
            'nim',
            'created_at',
            'updated_at',
        ],
    ]) ?>

            </div>
        </div>

    </div>
</div>